### ISSUE TITLE
Composer is broken: bower-asset/pushstream dev-master not found

### ISSUE THREAD

**Issue by gb5256** [dizews/yii2-push-stream#3]
Hi,
I see an older issue about this, and then you have changed the dependency from master do dev-master.
But this is right now not working.

This is the error I get:
Problem 1
    - Installation request for dizews/yii2-push-stream dev-master -> satisfiable by dizews/yii2-push-stream[dev-master].
    - dizews/yii2-push-stream dev-master requires bower-asset/pushstream dev-master -> no matching package found.

**Comment by dizews** [comment]
@gb5256 hello, I saw that you fixed this problem, you can make PR.
